language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed YOUR_DOCKER_HUB/udagram-api-feed
  - docker tag udagram-api-user YOUR_DOCKER_HUB/udagram-api-user
  - docker tag udagram-frontend YOUR_DOCKER_HUB/udagram-frontend
  - docker tag udagram-reverseproxy YOUR_DOCKER_HUB/reverseproxy

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/udagram-api-feed
  - docker push YOUR_DOCKER_HUB/udagram-api-user
  - docker push YOUR_DOCKER_HUB/udagram-frontend
  - docker push YOUR_DOCKER_HUB/reverseproxy

