language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t docker compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed bennydicta/udagram-api-feed
  - docker tag udagram-api-user bennydicta/udagram-api-user
  - docker tag udagram-frontend bennydicta/udagram-frontend
  - docker tag reverseproxy bennydicta/reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bennydicta/udagram-api-feed
  - docker push bennydicta/udagram-api-user
  - docker push bennydicta/udagram-frontend
  - docker push bennydicta/reverseproxy 
